const kosovoCities = [
  "Prishtina",
  "Prizren",
  "Ferizaj",
  "Peja",
  "Gjakova",
  "Gjilan",
  "Mitrovica",
  "Vushtrri",
  "Podujeva",
  "Drenas",
  "Other",
] as const;
const albaniaCities = [
  "Tirana",
  "Durres",
  "Vlore",
  "Shkoder",
  "Elbasan",
  "Fier",
  "Korce",
  "Berat",
] as const;
const macedoniaCities = [
  "Skopje",
  "Tetovo",
  "Gostivar",
  "Kumanovo",
  "Bitola",
  "Ohrid",
  "Prilep",
  "Struga",
] as const;
const montenegroCities = [
  "Podgorica",
  "Ulcinj",
  "Bar",
  "Budva",
  "Niksic",
  "Herceg Novi",
] as const;

export const countries = [
  {
    id: "xk",
    names: { sq: "Kosovë", en: "Kosovo", de: "Kosovo" },
    cities: kosovoCities,
  },
  {
    id: "al",
    names: { sq: "Shqipëri", en: "Albania", de: "Albanien" },
    cities: albaniaCities,
  },
  {
    id: "mk",
    names: { sq: "Maqedonia e Veriut", en: "North Macedonia", de: "Nordmazedonien" },
    cities: macedoniaCities,
  },
  {
    id: "me",
    names: { sq: "Mali i Zi", en: "Montenegro", de: "Montenegro" },
    cities: montenegroCities,
  },
] as const;

export type CountryId = (typeof countries)[number]["id"];
export const cities = [
  ...kosovoCities,
  ...albaniaCities,
  ...macedoniaCities,
  ...montenegroCities,
] as const;

export function countryById(id?: string) {
  return countries.find((country) => country.id === id);
}

export function countryForCity(city?: string) {
  if (!city) return undefined;
  return countries.find((country) =>
    (country.cities as readonly string[]).includes(city),
  );
}

export function countryName(
  country: (typeof countries)[number],
  locale: string,
) {
  return country.names[locale as Locale] ?? country.names.en;
}
export const locales = ["sq", "en", "de"] as const;
export type Locale = (typeof locales)[number];
export function localeOf(value?: string): Locale {
  return locales.includes(value as Locale) ? (value as Locale) : "sq";
}
export function translated(
  rows: { locale: string; name?: string; label?: string }[],
  locale: string,
) {
  const row =
    rows.find((r) => r.locale === locale) ??
    rows.find((r) => r.locale === "en") ??
    rows[0];
  return row?.name ?? row?.label ?? "";
}
export const copy = {
  sq: {
    search: "Kërko",
    sell: "Publiko shpallje",
    browse: "Kategoritë",
    shops: "Dyqanet",
    account: "Llogaria ime",
    favorites: "Preferuarat",
    login: "Kyçu",
    home: "Ballina",
    listingPage: "Shpallje",
    description: "Përshkrimi",
    additionalInfo: "Të dhëna shtesë",
    attribute: "Atributi",
    details: "Detajet",
    condition: "Gjendja",
    noAdditionalInfo: "Nuk ka të dhëna shtesë.",
    forSale: "Në shitje",
    wanted: "Kërkohet",
    negotiable: "I diskutueshëm",
    listed: "Publikuar",
    visitShop: "Shiko dyqanin",
    noPublicPhone: "Shitësi nuk ka ndarë një numër publik.",
    meetSafely: "Takohuni me kujdes.",
    meetSafelyText:
      "Kontrolloni sendin para pagesës. Mos e ndani fjalëkalimin ose kodet e verifikimit.",
    saveListing: "Ruaj shpalljen",
    shareListing: "Ndaj",
    messageSeller: "Mesazh shitësit",
    manageListing: "Menaxho shpalljen",
    callSeller: "Telefono",
    seller: "Shitësi",
    relatedEyebrow: "Shpallje të ngjashme",
    relatedLead: "Eksploro",
    relatedAccent: "shpalljet e ngjashme",
    headline: "Gjej diçka të mirë.",
    subhead: "Afër teje.",
    intro:
      "Nga gjërat e përditshme te gjetjet e veçanta. Bli dhe shit në komunitetin tënd.",
    latest: "Zbulo shpalljet",
    all: "Të gjitha",
    private: "Privat",
    business: "Biznes",
    verified: "Biznes i verifikuar",
    company: "Kompani",
    shopInfo: "Informacioni i dyqanit",
    availableListings: "Shpalljet e disponueshme",
    shopEmptyListings: "Ky dyqan s’ka shpallje aktive ende.",
    address: "Adresa",
    openingHours: "Orari i punës",
    legalName: "Emri ligjor",
    memberSince: "Anëtar që nga",
    reviewedOn: "I vlerësuar që nga",
    phoneLabel: "Telefoni",
    emailLabel: "Email",
    location: "Vendi",
    changeCountry: "Ndrysho vendin",
    allInCountry: "Gjithë {country}",
    query: "Çfarë po kërkon?",
    categoryField: "Kategoritë",
    allCategories: "Të gjitha kategoritë",
    categories: "Shfleto sipas kategorisë",
    empty: "Nuk u gjet asnjë shpallje.",
    clear: "Pastro filtrat",
    results: "shpallje",
    previous: "Prapa",
    next: "Tjetra",
    view: "Shiko shpalljen",
    shopCtaTitle: "Biznesi yt, më afër klientëve.",
    shopCtaText: "Hap dyqanin. Jepi inventarit një shtëpi.",
    shopCtaButton: "Hap dyqanin",
    allCities: "Gjithë Kosova",
    citySearch: "Kërko qytetin",
    cityEmpty: "Nuk u gjet asnjë qytet.",
    heroTrust1: "Shpallje të kontrolluara",
    heroTrust2: "Çmime të mira",
    heroTrust3: "Nga komuniteti",
    decorTitle: "Le ta dekorojmë shtëpinë tënde.",
    decorButton: "Shfleto",
    techTitle: "Përditëso teknologjinë tënde.",
    familyTitle: "Gjithçka për fëmijët e tu.",
  },
  en: {
    search: "Search",
    sell: "Post a listing",
    browse: "Categories",
    shops: "Shops",
    account: "Account",
    favorites: "Favorites",
    login: "Sign In",
    home: "Home",
    listingPage: "Listing",
    description: "Description",
    additionalInfo: "Additional information",
    attribute: "Attribute",
    details: "Details",
    condition: "Condition",
    noAdditionalInfo: "No additional information.",
    forSale: "For sale",
    wanted: "Wanted",
    negotiable: "Negotiable",
    listed: "Listed",
    visitShop: "Visit shop",
    noPublicPhone: "The seller has not shared a public phone number.",
    meetSafely: "Meet safely.",
    meetSafelyText:
      "Inspect the item before paying. Never share your password or verification codes.",
    saveListing: "Save listing",
    shareListing: "Share",
    messageSeller: "Message seller",
    manageListing: "Manage your listing",
    callSeller: "Call",
    seller: "Seller",
    relatedEyebrow: "Related listings",
    relatedLead: "Explore",
    relatedAccent: "related listings",
    headline: "Find something good.",
    subhead: "Closer to home.",
    intro:
      "From everyday essentials to unexpected finds. Buy and sell in your community.",
    latest: "Discover listings",
    all: "All sellers",
    private: "Private",
    business: "Business",
    verified: "Verified business",
    company: "Company",
    shopInfo: "Shop information",
    availableListings: "Available listings",
    shopEmptyListings: "This shop has no active listings yet.",
    address: "Address",
    openingHours: "Opening hours",
    legalName: "Legal name",
    memberSince: "Member since",
    reviewedOn: "Reviewed on",
    phoneLabel: "Phone",
    emailLabel: "Email",
    location: "Location",
    changeCountry: "Change country",
    allInCountry: "All of {country}",
    query: "What are you looking for?",
    categoryField: "Categories",
    allCategories: "All categories",
    categories: "Explore by category",
    empty: "No listings found.",
    clear: "Clear filters",
    results: "listings",
    previous: "Previous",
    next: "Next",
    view: "View listing",
    shopCtaTitle: "Your business, closer to customers.",
    shopCtaText: "Open your shop. Give your inventory a home.",
    shopCtaButton: "Open a shop",
    allCities: "All cities",
    citySearch: "Search a city",
    cityEmpty: "No cities found.",
    heroTrust1: "Reviewed listings",
    heroTrust2: "Great prices",
    heroTrust3: "From the community",
    decorTitle: "Let's decorate your house.",
    decorButton: "Browse",
    techTitle: "Upgrade your everyday tech.",
    familyTitle: "Everything for your little ones.",
  },
  de: {
    search: "Suchen",
    sell: "Anzeige erstellen",
    browse: "Kategorien",
    shops: "Shops",
    account: "Mein Konto",
    favorites: "Favoriten",
    login: "Anmelden",
    home: "Startseite",
    listingPage: "Anzeige",
    description: "Beschreibung",
    additionalInfo: "Zusätzliche Informationen",
    attribute: "Attribut",
    details: "Details",
    condition: "Zustand",
    noAdditionalInfo: "Keine zusätzlichen Informationen.",
    forSale: "Zu verkaufen",
    wanted: "Gesucht",
    negotiable: "Verhandelbar",
    listed: "Eingestellt",
    visitShop: "Shop besuchen",
    noPublicPhone: "Der Anbieter hat keine öffentliche Telefonnummer angegeben.",
    meetSafely: "Sicher treffen.",
    meetSafelyText:
      "Prüfe den Artikel vor der Zahlung. Teile niemals Passwort oder Bestätigungscodes.",
    saveListing: "Anzeige speichern",
    shareListing: "Teilen",
    messageSeller: "Anbieter schreiben",
    manageListing: "Anzeige verwalten",
    callSeller: "Anrufen",
    seller: "Anbieter",
    relatedEyebrow: "Ähnliche Anzeigen",
    relatedLead: "Entdecke",
    relatedAccent: "ähnliche Anzeigen",
    headline: "Entdecke etwas Gutes.",
    subhead: "Ganz in deiner Nähe.",
    intro:
      "Vom Alltäglichen bis zum besonderen Fund. Kaufe und verkaufe in deiner Nachbarschaft.",
    latest: "Anzeigen entdecken",
    all: "Alle Anbieter",
    private: "Privat",
    business: "Gewerblich",
    verified: "Geprüftes Gewerbe",
    company: "Unternehmen",
    shopInfo: "Shop-Informationen",
    availableListings: "Verfügbare Anzeigen",
    shopEmptyListings: "Dieser Shop hat noch keine aktiven Anzeigen.",
    address: "Adresse",
    openingHours: "Öffnungszeiten",
    legalName: "Firmenname",
    memberSince: "Mitglied seit",
    reviewedOn: "Geprüft am",
    phoneLabel: "Telefon",
    emailLabel: "E-Mail",
    location: "Ort",
    changeCountry: "Land ändern",
    allInCountry: "Ganz {country}",
    query: "Was suchst du?",
    categoryField: "Kategorien",
    allCategories: "Alle Kategorien",
    categories: "Kategorien entdecken",
    empty: "Keine Anzeigen gefunden.",
    clear: "Filter zurücksetzen",
    results: "Anzeigen",
    previous: "Zurück",
    next: "Weiter",
    view: "Anzeige ansehen",
    shopCtaTitle: "Dein Business, näher an den Kunden.",
    shopCtaText: "Eröffne deinen Shop. Gib deinem Inventar ein Zuhause.",
    shopCtaButton: "Shop eröffnen",
    allCities: "Alle Städte",
    citySearch: "Stadt suchen",
    cityEmpty: "Keine Städte gefunden.",
    heroTrust1: "Geprüfte Anzeigen",
    heroTrust2: "Gute Preise",
    heroTrust3: "Von der Gemeinschaft",
    decorTitle: "Lass uns dein Zuhause einrichten.",
    decorButton: "Entdecken",
    techTitle: "Bring deine Technik auf den neuesten Stand.",
    familyTitle: "Alles für die Kleinen.",
  },
};
export function money(cents: number | null) {
  return cents === null
    ? "Me marrëveshje / On request"
    : new Intl.NumberFormat("de-DE", {
        style: "currency",
        currency: "EUR",
        maximumFractionDigits: cents % 100 ? 2 : 0,
      }).format(cents / 100);
}
export function optionLabel(
  option: { value: string; labels: Record<string, string> },
  locale: string,
) {
  return option.labels[locale] ?? option.labels.en ?? option.value;
}
