// Category_Translations_EN_DE (2).pdf, pages 1–4. IDs retained where possible.
// English and German follow the reference; Albanian is translated for this app.
export const groups = [
  {
    id: "tickets",
    names: ["Bileta", "Tickets", "Tickets & Eintrittskarten"],
    icon: "Ticket",
    children: [
      ["concerts", "Koncerte", "Concerts", "Konzerte"],
      ["theatre-music", "Teatër dhe muzikë", "Theatre & Musik", "Theater & Musik"],
      ["vouchers", "Kuponë", "Voucher", "Gutscheine"],
      ["sport-tickets", "Sport", "Sport", "Sport"],
    ],
  },
  {
    id: "home",
    names: ["Shtëpi dhe kopsht", "Home & Garden", "Haus & Garten"],
    icon: "Armchair",
    children: [
      ["furniture", "Dhomë ndenjeje", "Living room", "Wohnzimmer"],
      [
        "appliances",
        "Kuzhinë dhe dhomë ngrënieje",
        "Kitchen & Dining room",
        "Küche & Esszimmer",
      ],
      ["bathroom", "Banjë", "Bathroom", "Badezimmer"],
      ["home-office", "Zyrë", "Office", "Büro"],
      ["decoration", "Dekorime", "Decoration", "Dekoration"],
      ["bedroom", "Dhomë gjumi", "Bedroom", "Schlafzimmer"],
      ["lighting", "Llamba dhe ndriçim", "Lamps & Lightning", "Lampen & Beleuchtung"],
      [
        "power-tools",
        "Punime dhe riparime vetjake",
        "DIY",
        "Heimwerken & Do-It-Yourself",
      ],
      ["home-textiles", "Tekstile shtëpiake", "Home Textiles", "Heimtextilien"],
      [
        "garden",
        "Pajisje kopshti dhe bimë",
        "Garden accessories & plants",
        "Gartenzubehör & Pflanzen",
      ],
      [
        "home-garden-service",
        "Shërbime për shtëpi dhe kopsht",
        "Home & Garden Service",
        "Dienstleistungen Haus & Garten",
      ],
    ],
  },
  {
    id: "business-equipment",
    names: ["Biznes dhe pajisje", "Business & Equipment", "Gewerbe & Einzelhandel"],
    icon: "BriefcaseBusiness",
    children: [
      ["machines", "Makineri", "Machine", "Maschinen"],
      ["office-supplies", "Pajisje zyre", "Office", "Bürobedarf"],
      ["agriculture", "Bujqësi", "Agriculture", "Landwirtschaft"],
    ],
  },
  {
    id: "auto",
    names: ["Automjete, biçikleta dhe varka", "Auto", "Auto, Rad & Boot"],
    icon: "Car",
    children: [
      ["cars", "Vetura", "Cars", "Autos"],
      ["bicycles", "Biçikleta", "Bicycles", "Fahrräder"],
      ["motorcycles", "Motoçikleta", "Motorcycles", "Motorräder"],
      ["boats", "Varka", "Boats", "Boote"],
      ["car-parts", "Pjesë dhe aksesorë veturash", "Car parts", "Autoteile & Zubehör"],
    ],
  },
  {
    id: "electronics",
    names: ["Elektronikë", "Electronics", "Elektronik"],
    icon: "Laptop",
    children: [
      [
        "phones",
        "Telefona dhe tableta",
        "Mobile phones & Tablets",
        "Smartphones & Tablets",
      ],
      [
        "computers",
        "Kompjuterë dhe laptopë",
        "PCs, Laptop & Notebooks",
        "PCs, Laptops & Notebooks",
      ],
      ["software", "Programe kompjuterike", "Software", "Software"],
      ["tvs", "Televizorë", "TVs", "TV & Fernseher"],
      ["gaming", "Videolojëra dhe konzola", "Gaming", "Videospiele & Konsolen"],
      [
        "wearables",
        "Pajisje inteligjente dhe aksesorë",
        "Wearables accessories",
        "Wearables & Zubehör",
      ],
      ["audio", "Audio dhe fotografi", "Audio & Photo", "Audio & Foto"],
      ["computer-parts", "Pjesë kompjuteri", "Computer parts", "PC-Komponenten"],
    ],
  },
  {
    id: "family",
    names: ["Familje, fëmijë dhe bebe", "Family, Kid & Baby", "Familie, Kind & Baby"],
    icon: "Baby",
    children: [
      [
        "children-clothing",
        "Rroba për bebe dhe fëmijë",
        "Baby & Children’s clothing",
        "Baby- & Kinderkleidung",
      ],
      [
        "children-shoes",
        "Këpucë për bebe dhe fëmijë",
        "Baby & Children’s shoes",
        "Baby- & Kinderschuhe",
      ],
      ["toys", "Lodra", "Toys", "Spielzeug"],
      ["mom-baby", "Nëna dhe bebja", "Mom & Baby", "Mutter & Baby"],
      ["children-furniture", "Mobilie për fëmijë", "Furniture", "Kindermöbel"],
      [
        "baby-essentials",
        "Gjërat e para për bebe",
        "Baby essentials",
        "Baby-Erstausstattung",
      ],
      ["baby", "Pajisje për bebe", "Baby equipment", "Babyausstattung"],
      ["mascots", "Maskota", "Mascots", "Maskottchen"],
      [
        "elderly-care",
        "Kujdes për të moshuarit",
        "Elderly care",
        "Seniorenbetreuung & Pflege",
      ],
    ],
  },
  {
    id: "pets",
    names: ["Kafshë shtëpiake", "Pets", "Haustiere"],
    icon: "PawPrint",
    children: [
      ["dogs", "Qen", "Dogs", "Hunde"],
      ["cats", "Mace", "Cats", "Katzen"],
      ["fish", "Peshq", "Fish", "Fische"],
      ["small-animals", "Kafshë të vogla", "Small animals", "Kleintiere"],
      ["farm-animals", "Kafshë ferme", "Farm animals", "Nutztiere"],
      ["horses", "Kuaj", "Horses", "Pferde"],
      [
        "pet-care",
        "Kujdes dhe aksesorë për kafshë",
        "Pet care & Accessories",
        "Tierpflege & Zubehör",
      ],
    ],
  },
  {
    id: "sports",
    names: [
      "Kohë e lirë, hobi dhe fqinjësi",
      "Free time, Hobbies & Neighborhood",
      "Freizeit, Hobby & Nachbarschaft",
    ],
    icon: "Dumbbell",
    children: [
      ["art-antiques", "Art dhe antikitete", "Art & Antiques", "Kunst & Antiquitäten"],
      ["spirituality", "Spiritualitet", "Spirituality", "Esoterik & Spiritualität"],
      ["food-drinks", "Ushqime dhe pije", "Food & Drinks", "Essen & Trinken"],
      ["handmade", "Punime me dorë", "Handcraft & Handmade", "Handarbeit & Bastelei"],
      [
        "travel-events",
        "Pajisje udhëtimi dhe eventesh",
        "Travel & Event Essentials",
        "Reise- & Eventzubehör",
      ],
      ["outdoors", "Sport dhe kamping", "Sport & Camping", "Sport & Camping"],
    ],
  },
  {
    id: "fashion-beauty",
    names: ["Modë dhe bukuri", "Mode & Beauty", "Mode & Schönheit"],
    icon: "Shirt",
    children: [
      ["women-clothing", "Rroba për gra", "Women’s clothes", "Damenbekleidung"],
      ["men-clothing", "Rroba për burra", "Man’s clothes", "Herrenbekleidung"],
      [
        "beauty-health",
        "Bukuri dhe shëndet",
        "Beauty & Health",
        "Schönheit & Gesundheit",
      ],
      ["women-shoes", "Këpucë për gra", "Women’s shoes", "Damenschuhe"],
      ["men-shoes", "Këpucë për burra", "Man’s shoes", "Herrenschuhe"],
      [
        "bags-accessories",
        "Çanta dhe aksesorë",
        "Bags & Accessories",
        "Tasche & Accessoires",
      ],
      ["watches-jewelry", "Ora dhe bizhuteri", "Watches & Jewelry", "Uhren & Schmuck"],
    ],
  },
  {
    id: "books",
    names: ["Muzikë, filma dhe libra", "Musik, Film & Books", "Musik, Film & Bücher"],
    icon: "BookOpen",
    children: [
      ["books-media", "Libra dhe revista", "Books & Magazines", "Bücher & Zeitschriften"],
      ["films-dvd", "Filma dhe DVD", "Film & DVD", "Filme & DVDs"],
      [
        "textbooks",
        "Libra shkollorë dhe universitarë",
        "Textbooks, School & University",
        "Fachbücher, Schule & Universität",
      ],
      ["music-cds", "Muzikë dhe CD", "Musik & CDs", "Musik & CDs"],
      ["instruments", "Instrumente muzikore", "Music Instruments", "Musikinstrumente"],
      ["comics", "Stripa", "Comics", "Comics"],
    ],
  },
  {
    id: "give-away",
    names: ["Falas", "Give away", "Zu verschenken"],
    icon: "Gift",
    children: [
      [
        "free-items",
        "Artikuj falas",
        "Free / Give away items",
        "Kostenlose Artikel / Zu verschenken",
      ],
    ],
  },
];
export const definitions = [
  {
    categoryId: "phones",
    key: "brand",
    type: "SELECT",
    labels: ["Marka", "Brand", "Marke"],
    options: ["Apple", "Samsung", "Google", "Xiaomi", "Other"],
    required: true,
  },
  {
    categoryId: "phones",
    key: "storage",
    type: "NUMBER",
    labels: ["Hapësira", "Storage", "Speicher"],
    unit: "GB",
    min: 1,
    max: 4096,
    required: true,
  },
  {
    categoryId: "phones",
    key: "model",
    type: "TEXT",
    labels: ["Modeli", "Model", "Modell"],
    required: true,
  },
  {
    categoryId: "computers",
    key: "ram",
    type: "NUMBER",
    labels: ["Memoria RAM", "RAM", "Arbeitsspeicher"],
    unit: "GB",
    min: 1,
    max: 1024,
    required: true,
  },
  {
    categoryId: "furniture",
    key: "material",
    type: "SELECT",
    labels: ["Materiali", "Material", "Material"],
    options: ["Wood", "Metal", "Fabric", "Leather", "Other"],
    required: true,
  },
  {
    categoryId: "furniture",
    key: "width",
    type: "NUMBER",
    labels: ["Gjerësia", "Width", "Breite"],
    unit: "cm",
    min: 1,
    max: 1000,
    required: false,
  },
  {
    categoryId: "power-tools",
    key: "cordless",
    type: "BOOLEAN",
    labels: ["Pa kabllo", "Cordless", "Kabellos"],
    required: false,
  },
];
